aridoza/redd-clone

- pom.xml
- seed.sh
- seed_db.sql
- src/main/java/com/ga/config/AppConfig.java
- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/dao/UserDao.java
- src/main/java/com/ga/dao/UserDaoImpl.java
- src/main/java/com/ga/entity/User.java
- src/main/java/com/ga/service/UserService.java
- src/main/java/com/ga/service/UserServiceImpl.java
* Implemented routes for list all users, signup, login, delete user
* Implemented logic for route handling
* Refactored AppConfig > dataSource() with appropriate db name
* Added seed.sh file and seed_db.sql file for easier reseeding of database users table
> Pre-Auth Users

- src/main/java/com/ga/entity/Post.java
- src/main/java/com/ga/entity/User.java
* Join working between Post and User
* Refactor code with usernames being parsed from JWT
> Join users posts

- src/main/java/com/ga/config/SecurityConfig.java
- src/main/java/com/ga/controller/CommentController.java
- src/main/java/com/ga/controller/PostController.java
- src/main/java/com/ga/dao/CommentDao.java
- src/main/java/com/ga/dao/CommentDaoImpl.java
- src/main/java/com/ga/dao/PostDao.java
- src/main/java/com/ga/dao/PostDaoImpl.java
- src/main/java/com/ga/entity/Comment.java
- src/main/java/com/ga/entity/Post.java
- src/main/java/com/ga/service/CommentService.java
- src/main/java/com/ga/service/CommentServiceImpl.java
- src/main/java/com/ga/service/PostService.java
- src/main/java/com/ga/service/PostServiceImpl.java
- src/main/java/com/ga/service/UserServiceImpl.java
updated createComment method in CommentService to take in username
> Comments branch

- seed_db.sql
- src/main/java/com/ga/config/JwtRequestFilter.java
- src/main/java/com/ga/config/SecurityConfig.java
- src/main/java/com/ga/controller/CommentController.java
- src/main/java/com/ga/controller/PostController.java
- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/dao/CommentDao.java
- src/main/java/com/ga/dao/CommentDaoImpl.java
- src/main/java/com/ga/dao/PostDao.java
- src/main/java/com/ga/dao/PostDaoImpl.java
- src/main/java/com/ga/entity/Comment.java
- src/main/java/com/ga/entity/Post.java
- src/main/java/com/ga/service/CommentService.java
- src/main/java/com/ga/service/CommentServiceImpl.java
- src/main/java/com/ga/service/PostService.java
- src/main/java/com/ga/service/PostServiceImpl.java
- src/main/java/com/ga/service/UserServiceImpl.java
* Able to return username to the client along with token on signup and login
* Updated Seed files for auto inserting users and posts
> Auth get username

- src/main/java/com/ga/controller/UserProfileController.java
- src/main/java/com/ga/dao/UserDao.java
- src/main/java/com/ga/dao/UserDaoImpl.java
- src/main/java/com/ga/dao/UserProfileDao.java
- src/main/java/com/ga/dao/UserProfileDaoImpl.java
- src/main/java/com/ga/entity/User.java
- src/main/java/com/ga/entity/UserProfile.java
- src/main/java/com/ga/service/UserProfileService.java
- src/main/java/com/ga/service/UserProfileServiceImpl.java
* Added functionality for UserProfile
* User Profile is joined to Users, one to one
> User profile

- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/dao/UserDao.java
- src/main/java/com/ga/dao/UserDaoImpl.java
- src/main/java/com/ga/service/UserService.java
- src/main/java/com/ga/service/UserServiceImpl.java
added methods to handle login via email, refactored login method
> login by email working

- src/main/java/com/ga/config/SecurityConfig.java
- src/main/java/com/ga/controller/CommentController.java
- src/main/java/com/ga/controller/PostController.java
- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/controller/UserProfileController.java
- src/main/java/com/ga/service/UserServiceImpl.java
* Added method level authorization
* fixed minor typo in UserServiceImpl
> implemented auth, fixed minor typo

- src/main/java/com/ga/config/AppConfig.java
- src/main/java/com/ga/controller/CommentController.java
- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/dao/CommentDao.java
- src/main/java/com/ga/dao/CommentDaoImpl.java
- src/main/java/com/ga/service/CommentService.java
- src/main/java/com/ga/service/CommentServiceImpl.java
* Implemented getCommentsByUsername 
* Username is grabbed from the incoming token through the request headers
* Refactored createComment
* createComment is grabbing the username from the incoming token
> Get Comments By Username

- src/main/java/com/ga/config/AppConfig.java
- src/main/java/com/ga/controller/PostController.java
- src/main/java/com/ga/dao/CommentDao.java
- src/main/java/com/ga/dao/CommentDaoImpl.java
- src/main/java/com/ga/service/CommentService.java
- src/main/java/com/ga/service/CommentServiceImpl.java
added logic to get comments by postId
> Comments by post

- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/dao/PostDao.java
- src/main/java/com/ga/dao/PostDaoImpl.java
- src/main/java/com/ga/service/PostService.java
- src/main/java/com/ga/service/PostServiceImpl.java
* GetPostsByUser works
* Username is taken from token
> implemented get posts by username from token

- pom.xml
- src/main/java/com/ga/controller/CommentController.java
- src/main/java/com/ga/controller/PostController.java
- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/controller/UserProfileController.java
added @CrossOrigin annotation to all controllers for CORS error resolution
> added cors to all controllers

- src/main/java/com/ga/controller/PostController.java
- src/main/java/com/ga/dao/CommentDaoImpl.java
- src/main/java/com/ga/dao/PostDaoImpl.java
- src/main/java/com/ga/dao/UserDaoImpl.java
- src/main/java/com/ga/entity/Comment.java
- src/main/java/com/ga/entity/Post.java
- src/main/java/com/ga/entity/User.java
- src/main/java/com/ga/entity/UserProfile.java
- src/main/java/com/ga/service/UserServiceImpl.java
frontend functionality updated to work with redd-clone backend
> Frontend route updates

- src/main/java/com/ga/config/SecurityConfig.java
- src/main/java/com/ga/controller/UserProfileController.java
- src/main/java/com/ga/service/UserProfileServiceImpl.java
resolved CORS issue with profile routes
> solved user profile CORS issues

- src/test/java/com/ga/controller/CommentControllerTest.java
- src/test/java/com/ga/controller/CommentDaoTest.java
- src/test/java/com/ga/controller/CommentServiceTest.java
created files for comment testing
> created files for comment testing

- pom.xml
- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/entity/JwtResponse.java
- src/main/java/com/ga/service/UserService.java
- src/main/java/com/ga/service/UserServiceImpl.java
- src/test/java/com/ga/controller/UserControllerTest.java
- src/test/java/com/ga/dao/UserDaoTest.java
- src/test/java/com/ga/service/UserServiceTest.java
* Refactored Signup Login returns for the way that the JWT was being returned with username
* Added some tests for User
> User tests

- pom.xml
- src/main/java/com/ga/controller/PostController.java
- src/test/java/com/ga/controller/CommentControllerTest.java
- src/test/java/com/ga/controller/PostControllerTest.java
- src/test/java/com/ga/controller/TestUtil.java
- src/test/java/com/ga/dao/CommentDaoTest.java
- src/test/java/com/ga/dao/PostDaoTest.java
- src/test/java/com/ga/service/CommentServiceTest.java
- src/test/java/com/ga/service/PostServiceTest.java
completed Post testing (Controller, Service, Dao)
Completed Comment Testing (Service)
working on Comment Dao and Controller testing
> Posts testing

- pom.xml
- src/main/java/com/ga/controller/PostController.java
- src/test/java/com/ga/controller/CommentControllerTest.java
- src/test/java/com/ga/controller/PostControllerTest.java
- src/test/java/com/ga/controller/TestUtil.java
- src/test/java/com/ga/dao/CommentDaoTest.java
- src/test/java/com/ga/dao/PostDaoTest.java
- src/test/java/com/ga/dao/UserDaoTest.java
- src/test/java/com/ga/service/CommentServiceTest.java
- src/test/java/com/ga/service/PostServiceTest.java
- src/test/java/com/ga/service/UserServiceTest.java
* Most tests for UserController complete and passing
* Most tests for UserService complete and passing
* All tests for UserDao complete and passing
* Finish tests for getPostsByUsername and getCommentsByUsername in UserController
* Finish tests for loadUserByUsername and loadUserByEmail in UserServices
> User tests continued

- src/main/java/com/ga/controller/UserController.java
- src/main/java/com/ga/controller/UserProfileController.java
- src/main/java/com/ga/dao/UserDaoImpl.java
- src/main/java/com/ga/dao/UserProfileDaoImpl.java
- src/main/java/com/ga/service/UserProfileServiceImpl.java
- src/test/java/com/ga/controller/UserControllerTest.java
- src/test/java/com/ga/controller/UserProfileControllerTest.java
- src/test/java/com/ga/dao/UserDaoTest.java
- src/test/java/com/ga/dao/UserProfileDaoTest.java
- src/test/java/com/ga/repository/UserProfileDaoStub.java
- src/test/java/com/ga/service/UserProfileServiceStub.java
- src/test/java/com/ga/service/UserProfileServiceTest.java
- src/test/java/com/ga/service/UserServiceTest.java
* Completed tests for UserProfileController and tests successful
* Completed tests for UserProfileService and tests successful
* Completed tests for UserProfileDao and tests successful
> User profile tests

- src/main/java/com/ga/service/UserServiceImpl.java
* Quick bug fix for login returning null username in UserServiceImpl
> minor bug fix for login returning null username

- src/test/java/com/ga/controller/UserControllerTest.java
* Added test for list users in UsersController
> User tests continued 02

- src/test/java/com/ga/controller/CommentControllerTest.java
- src/test/java/com/ga/dao/CommentDaoTest.java
getComments and deleteComments test working in commentController test
working on createComment test in commentController
> Remaining comments testing
